### ISSUE TITLE
feature: seções "mais visualizados" e "últimos posts"

### ISSUE THREAD

**Issue by ilucaslima** [ilucaslima/juniando-web#15]
# Desenvolver as Seções da Home: "Mais Visualizados" e "Últimos Posts"

As seções "Mais Visualizados" e "Últimos Posts" serão responsáveis por exibir conteúdos destacados da aplicação, organizados em formato de cards. Ambas as seções devem seguir o mesmo layout e diferenciar-se apenas pelo tipo de conteúdo exibido.

## Requisitos

Cada seção deve:

1. Conter um **título descritivo** no topo da seção (ex.: "Mais Visualizados", "Últimos Posts").
2. Exibir **6 cards**, com as seguintes informações em cada card:
   - Imagem destacada.
   - Título do post.
   - Descrição limitada a 100 caracteres.
   - Nome do autor e data de publicação, exibidos em formato discreto.
3. Ser responsiva, garantindo que os cards sejam dispostos adequadamente em dispositivos móveis e desktops.
4. Seguir a identidade visual do projeto, utilizando as cores e fontes especificadas no design.

## Design de Referência

[Design das Seções](https://www.figma.com/design/WwQmhLnqDixu0ua6YGGv7z/Juniando?node-id=0-4&p=f&t=1fDepkvSvcs0SUmN-0)

## Critérios de Aceitação

- As seções devem ser inseridas na página inicial da aplicação.
- O layout das seções deve corresponder ao design fornecido.
- Os cards devem ser uniformes e exibir corretamente os conteúdos, mesmo com textos de tamanhos variados.

## Tecnologias

Next.js, Tailwind, e TypeScript

## Dificuldade Estimada

Média

## Informações Adicionais

Siga o padrão de branch: `feat/home-sections#<número-da-issue>`.

Qualquer dúvida, comente nesta issue.

## Tarefas Relacionadas

- [x] Implementar o layout das seções.
- [x] Adicionar os 6 cards em cada seção.
- [x] Garantir que os títulos e descrições nos cards sejam ajustados corretamente.
- [ ] Testar responsividade em diferentes tamanhos de tela.

**Comment by SidneyRoberto9** [comment]
Irei realizar essa Issue.
Data Prevista 23/12/2024

**Comment by SidneyRoberto9** [comment]
Pull Request feito @ilucaslima
