### ISSUE TITLE
feature: criar componente footer

### ISSUE THREAD

**Issue by ilucaslima** [ilucaslima/juniando-web#4]
Desenvolver o componente Footer seguindo as especificações abaixo. O Footer será responsável por exibir informações adicionais e links úteis do sistema.

Requisitos:
O Footer deve conter:

1. Uma seção com informações institucionais (Em baixo do componente colocar: Copyright © 2025 - Juniando
2. Ícones de redes sociais (ex.: LinkedIn, Twitter, GitHub) *sem* os links.
3. Deve ser responsivo, funcionando corretamente em dispositivos móveis e desktops.
4. Seguir a identidade visual do projeto, utilizando as cores e fontes especificadas no design.

Design de Referência:
[[Design do Footer](https://www.figma.com/design/WwQmhLnqDixu0ua6YGGv7z/Juniando?node-id=0-1&p=f&t=1fDepkvSvcs0SUmN-0)]

Critérios de Aceitação:
O componente deve ser inserido no layout da aplicação.
O layout deve corresponder ao design fornecido.

Tecnologias:
Next.js, Tailwind, e TypeScript

Dificuldade Estimada:
Baixa

Informações Adicionais:
Siga o padrão de branch: feat/footer-component#<número-da-issue>.

Qualquer dúvida, comente nesta issue.

Tarefas Relacionadas:
 - [x] Implementar o layout do Footer.
 - [x] Adicionar ícones de redes sociais.
 - [x] Testar responsividade em diferentes tamanhos de tela.

**Comment by leonardohernandesq** [comment]
Irei realizar essa Issue.
Data Prevista `22/12/2024`

**Comment by leonardohernandesq** [comment]
Essa feature foi finalizada, mas não consigo encerrar a task por não ser o criador.
