### ISSUE TITLE
feature: componente de assuntos relevantes

### ISSUE THREAD

**Issue by ilucaslima** [ilucaslima/juniando-web#5]
Desenvolver o componente Assuntos Relevantes seguindo as especificações abaixo. O componente será responsável por exibir uma lista de assuntos populares para que os usuários possam visualizar os temas destacados.

O componente deve:

1. Exibir uma lista de assuntos relevantes, como:
- JavaScript
- ReactJS
- VuewJS
- AngularJS

2. Cada assunto deve ser exibido como um link clicável.
3. As informações devem ser mockadas, já que não existe página ou links reais para os assuntos.
4. Seguir a identidade visual do projeto, utilizando as cores e fontes especificadas no design.
5. Deve ser responsivo, funcionando corretamente em dispositivos móveis e desktops.

Design de Referência:
[https://www.figma.com/design/WwQmhLnqDixu0ua6YGGv7z/Juniando?node-id=0-1&p=f&t=1fDepkvSvcs0SUmN-0]

Critérios de Aceitação:
A lista de assuntos deve ser exibida de acordo com o design fornecido.
Os links não devem redirecionar, mas devem ser visualmente estilizados como clicáveis.

Tecnologias:
Next.js, Tailwind, e TypeScript

Dificuldade Estimada:
Baixa

Informações Adicionais:
Siga o padrão de branch: feat/relevant-topics-component#<número-da-issue>.

Qualquer dúvida, comente nesta issue.

Tarefas Relacionadas:
- [ ] Implementar o layout do componente com a lista de assuntos.
- [ ] Mockar as informações dos assuntos relevantes.
- [ ] Testar responsividade em diferentes tamanhos de tela.

**Comment by SidneyRoberto9** [comment]
Irei realizar essa Issue.
Data Prevista 22/12/2024

**Comment by SidneyRoberto9** [comment]
Irei realizar essa Issue.
Data Prevista 22/12/2024

**Comment by SidneyRoberto9** [comment]
Pull request feito @ilucaslima

**Comment by ilucaslima** [comment]
Aprovado ✅
